### ISSUE TITLE
Remove Duration bug

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#430] opened 2022-06-27 12:45 UTC
**User input 1 (by Fredrik Liknes- sharepoint ID151):**
As a user of Flyt I would like to be able to remove times from cards so that I get the correct setup for my process mapping.

When attempting to remove times from cards today (27.06.22) the application crashes with "An error occurred on client". reloading the page get me back to where I was prior to the crash. 

https://user-images.githubusercontent.com/25986427/176108997-7d7c4714-6055-43f4-bfa7-87a90df772dc.mp4

**Comment by ofredstie** [comment] 2023-02-23 11:31
How to reproduce:
1. Add a new SubActivity or Waiting card
2. Add a duration and tab to unit dropdown
3. select one of the options and click on the X that appear next to the selected option



![Image](https://user-images.githubusercontent.com/3359842/220894188-fb5edb7d-87c1-44c1-917a-1bd73779a586.png)

**Comment by dansvend** [comment] 2023-04-24 12:22
@ofredstie Maybe you could have a chat with @VetleW if we should change up the design? Maybe have a red button on the right side of that row to remove duration from that card. And after duration is removed it could show a green button to be able to add duration?

**Comment by ofredstie** [comment] 2023-04-27 08:37
@dansvend Shouldn't that be registered as a new feature improvement issue? 

This is a bugfix and the "Clear" function is an integrated part of EDS Autocomplete component.

**Comment by KaterynaBasik** [comment] 2024-03-11 11:16
@QiJin-Bouvet could you plwase check, should be fixed

**Comment by QiJin-Bouvet** [comment] 2024-03-18 11:36
@nesadrian I am using Edge. The problem is not every time reproducible, but from time to time. And there is no console error or network requests fail when error happen.

**Comment by nesadrian** [comment] 2024-03-18 12:23
Thanks, I will look further into this issue when I have time

**Comment by nesadrian** [comment] 2024-06-04 09:50
@QiJin-Bouvet This is ready for test in [TEST](https://test.flyt.equinor.com/)

**Comment by nesadrian** [comment] 2024-06-05 13:13
@QiJin-Bouvet This is ready for test in [TEST](https://test.flyt.equinor.com/)

**Comment by QiJin-Bouvet** [comment] 2024-06-06 07:06
Tested in TEST env.
0 duration is accepted.

**Closed** 2024-06-06 07:23 UTC
Labels: bug, feedback, front-end
